# Generated by Django 4.2.1 on 2024-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authAPp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revokedtoken",
            name="created_at",
        ),
        migrations.AddField(
            model_name="revokedtoken",
            name="expiration_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revokedtoken",
            name="is_explicit",
            field=models.BooleanField(default=False),
        ),
    ]
