# Generated by Django 4.2.1 on 2024-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authAPp", "0002_remove_revokedtoken_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revokedtoken",
            name="expiration_time",
        ),
    ]
